services:
  gateway:
    build: ../../gateway
    ports: ["8080:8080"]
    environment:
      AUTH_SERVICE_URL: http://auth-service:4001
      USER_SERVICE_URL: http://user-service:4002
      NOTIFICATION_SERVICE_URL: http://notification-service:4003
      ANALYTICS_SERVICE_URL: http://analytics-service:4004
    depends_on: [auth-service, user-service, notification-service, analytics-service]
  auth-service:
    build: ../../services/auth-service
    expose: ["4001"]
  user-service:
    build: ../../services/user-service
    expose: ["4002"]
  notification-service:
    build: ../../services/notification-service
    expose: ["4003"]
  analytics-service:
    build: ../../services/analytics-service
    expose: ["4004"]
  prometheus:
    image: prom/prometheus:v3.5.0
    ports: ["9090:9090"]
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on: [gateway]
  grafana:
    image: grafana/grafana:12.1.0
    ports: ["3000:3000"]
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on: [prometheus]
